### ISSUE TITLE
Dialog submit behavior

### ISSUE THREAD

**Issue by Mellich** [Mellich/JukePi#48]
It should be possible to close a dialog by pressing 'Enter' (e.g. when creating a gap list). 
When selecting a gap list it would be nice to reduce the amount of buttons. Why not showing the content on single click in the list and loading the gap list by double clicking (with automated closing afterwards)?

**Comment by Haeldeus** [comment]
Added KeyListener to all (imo) Windows, where it was needed, if there are more, where those should be added, let me know.
Reducing the Buttons in the DisplayGaplistWindow is a thing we might have to discuss about. Is it intentional enough, that you load a List when you double click it? Both Features you mentioned are implemented with the last commit, but I would leave Show and Delete as Buttons in that Window, just to make sure, that everyone can use the Client without long terms of searching the Window for a possibility to load a List, because we wanted to make the Windows look fancier.
